### ISSUE TITLE
switch to esm

### ISSUE THREAD

**Issue by jimmywarting** [ImperatorOfIntellectualism/CHANapp#2]
https://github.com/ImperatorOfIntellectualism/CHANapp/blob/3959ec1db779525bb9b33e63f6190bcad762b7fe/KEKW/src/index.ts#L52

i guess your backend is pretty private so it's not something that would need to be publicly available so you could probably target latest node version and compile you typescript code to ESM by using {type: module} in package json and target the tsconfig to compile to esm instead of commonjs

that way you can also use top level await 👍 
and you don't need to use lazy dynamic `import('node-fetch')` or the hacky `_dynamicImport` that is required due to typescript compiler that rewrites `import()` to `require()`

**Comment by ImperatorOfIntellectualism** [comment]
I'm sorry, why are you posting this in issues? My project works perfectly (unlike yours, which literally doesn't work) because I value my reputation, and I would never publish something that doesn't work (unlike you by the way).

**Comment by jimmywarting** [comment]
keep it as cjs if you like it then
